### PR TITLE
Re-export instead of import and then export to optimize tree shaking

### PR DESCRIPTION
**Pull request by phaberest**
Hey Jason! 🙌🏻 

This should help avoiding the issue I encountered in #27 

NB: I could not run an `npm run test` as my connection right now is terrible and I need to download playwright data

### CODE REVIEW

**Comment by zerodevx** [comment]
Hey, thanks for your PR - but I'm not sure if single-line re-export is any different from an import-export... afaik they are semantically equivalent? 🤔 

Both syntax should be tree-shaken by bundlers.

**Comment by zerodevx** [comment]
I just tested with your changes in place, but seems like `FxParallax` is still included in the build. Trying to figure out what's going on. 🤷

**Comment by zerodevx** [comment]
This should be fixed with #29 - thanks!

**Comment by phaberest** [comment]
Awesome, well done! 🙌🏻 (sorry, fighting with the worst connection ever these days and have just read)

**Pull request closed without merging**
