### PR TITLE
Fixup "Art direction" docs in README.md

### PR DESCRIPTION
**Pull request by leoj3n**

### CODE REVIEW

**Comment by zerodevx** [comment]
Thanks! Could you just run `npm run format` on this so code indentation is normalised?

**Comment by leoj3n** [comment]
@zerodevx Ok think I have it correct hopefully you can squash the commits for merge.

**Comment by zerodevx** [comment]
No worries, will squash before merge so commit away!

> I have a problem with calling this section "Art Direction".

Hmm to me that's synonymous to "customised image selection" which is apt, but open to suggestions!

**Comment by leoj3n** [comment]
From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

> Common use cases for `<picture>`:
> - Art direction. Cropping or modifying images for different media conditions (for example, loading a simpler version of an image which has too many details, on smaller displays).
> - Offering alternative image formats, for cases where certain formats are not supported. Note: For example, newer formats like [AVIF](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#avif_image) or [WEBP](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#webp_image) have many advantages, but might not be supported by the browser.
> - Saving bandwidth and speeding page load times by loading the most appropriate image for the viewer's display.

It's for the later two of these three options that the `` component is utilizing `<picture>` here.

The [MDN guide about "Responsive images"](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) is all over the place:

> An improvement would be to display a cropped version of the image which displays the important details of the image when the site is viewed on a narrow screen. A second cropped image could be displayed for a medium-width screen device, like a tablet. The general problem whereby you want to serve different cropped images in that way, for various layouts, is commonly known as the art direction problem.
> 
> In addition, there is no need to embed such large images on the page if it is being viewed on a mobile screen. Doing so can waste bandwidth; in particular, mobile users don't want to waste bandwidth by downloading a large image intended for desktop users, when a small image would do for their device. Conversely, a small [raster image](https://developer.mozilla.org/en-US/docs/Glossary/Raster_image) starts to look grainy when displayed larger than its original size (a raster image is a set number of pixels wide and a set number of pixels tall, as we saw when we looked at [vector graphics](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web)). Ideally, multiple resolutions would be made available to the user's web browser. The browser could then determine the optimal resolution to load based on the screen size of the user's device. This is called the resolution switching problem.
> 
> To make things more complicated, some devices have high resolution screens that need larger images than you might expect to display nicely. This is essentially the same problem, but in a slightly different context.
>
> ...CSS arguably has better tools for responsive design than HTML...

The contradictory word salad here was more confusing than helpful when I was first reading up on "responsive images".

The [MDN `HTML/Element/picture` docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) linked above are much more clear and precise regarding `<picture>`.

Regardless, it looks like the consensus is to call usage of `<picture>/srcset/sizes` "responsive images". So, probably change this section header from "Art direction" to "Responsive Image Sizes".

Where you have the comment:

```html
<!-- If viewport is <=600px, use 480px as viewport width -->
```

This is a bit misleading. The "sizes" aren't the actual size of the viewport itself, the sizes are the size the `` will be at certain breakpoints, so I would maybe change that bit to read as:

```html
<!-- When the viewport is <=600px, tell the browser's image preprocessor that once the CSS for our design has been parsed and applied we expect the width of the image in our design to be 480px -->
```

Finally, I would remove the link to the confusing "Responsive images" guide, and instead link to the more clear `HTML/Element/picture` docs that are more in line with how "Responsive Images" are being utilized here.

**Comment by leoj3n** [comment]
Really even the MDN docs for `<picture>` are kind of lame... They just kind of randomly launch into talking about `sizes`:

> The sizes attribute is not mandatory when using srcset, but it is recommended to use it in order to provide additional information to the browser to help it select the best image source.
> 
> Without sizes, the browser will use the default size of the image as specified by its dimensions in pixels. This may not be the best fit for all devices, especially if the image is displayed on different screen sizes or in different contexts.
> 
> Please note that sizes will have its effect only if width dimension descriptors are provided with srcset instead of pixel ratio values (200w instead of 2x for example). For more information on using srcset, see the [Responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) documentation.

Without linking to further docs or showing any example, and aren't explicit in saying the `sizes=` should be on `<source>`.

They do have docs for [HTMLImageElement/sizes](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes) but they don't show any example of using `sizes` with `<picture>` and `<source>`.

I feel like they kind of dropped the ball on these docs.

**Comment by zerodevx** [comment]
> Isn't this advice all over the place and misguided or am I crazy?

Well, you know what they say - everyone has an opinion. 😆

`svelte-img` is really made to just use and forget IMO - it just comes with *sensible enough* defaults that are *performant enough*, yet *easy enough* to override; so consumers can quickly move on and spend time on the meaty stuff, like business logic.

Anyway, LGTM - will merge. Thanks so much for your contribution! 🙏

**Pull request merged**
